#------------------------------
# Create mastersheet of SPRING-FISH profiler data
#------------------------------

library(tidyverse)
library(lubridate)

# Create list of data files
datafiles <- list.files(path = "data/raw/experiment", 
                        pattern = ".csv", full.names = TRUE)

# Combine into one data frame and add a column with the enclosure name
master <- datafiles %>%
  setNames(nm = .) %>% # getting the file names from the list of files
  map_df(~read.csv(.x, sep = ";", skip = 3), .id = "file_name") %>% # create and join csvs
  mutate(enclosure = str_extract(file_name, "[A-Za-z]\\d+")) %>% # add a column with the enclosure number, pulled from the full file name
  select(-file_name) # remove column with the full file name

table(master$enclosure)

# Remove junk rows
master_cleaned <- master %>% 
  subset(water.temperature != "w_temp" &
         water.temperature != "water physics" &
         water.temperature != "EXO2-Multiprobe" &
         specified.depth != "m" &
         id != "Autogenerated Increment Value")

# Check that we have removed all of the junk rows
table(master_cleaned$specified.depth)

# Check structure of the data frame
str(master_cleaned)

# Convert appropriate columns to numeric and datetime
master_cleaned_2 <- master_cleaned %>%
  mutate_at(vars(specified.depth:number.of.measurements, version:phycoeritrin..RFU.), as.numeric) %>%
  mutate_at(vars(datetime, profile.datetime), as.POSIXct)

# Check structure of the data frame
str(master_cleaned_2)

# Add columns for doy, day, month, year, and time from datetime and profile.datetime columns
master_cleaned_3 <- master_cleaned_2 %>%
  mutate(doy_datetime = yday(datetime),
         day_datetime = day(datetime),
         month_datetime = month(datetime),
         year_datetime = year(datetime),
         time_datetime = paste(hour(datetime), minute(datetime), second(datetime), sep = ":")) %>%
  mutate(doy_profiledatetime = yday(profile.datetime),
         day_profiledatetime = day(profile.datetime),
         month_profiledatetime = month(profile.datetime),
         year_profiledatetime = year(profile.datetime),
         time_profiledatetime = paste(hour(profile.datetime), minute(profile.datetime), second(profile.datetime), sep = ":")) %>%
  mutate(test = doy_datetime - doy_profiledatetime)

# Do the datetime and profile.datetime dates always match exactly? 
table(master_cleaned_3$test)
# yes except for 3 occasions

# To do:
# Figure out which date and time to use
# Visualize dates we have data for for each enclosure
# Check for missing values
# Visualize correlated variables