#------------------------------
# Creating mastersheet of SPRING-FISH profiler data - junk code
#------------------------------

library(data.table)
library(tidyverse)
library(plyr)

# Make a list of all the files
datafiles <- list.files(path = "data/raw", 
                        pattern = ".csv", full.names = TRUE)

#test_L3_v2 <- testL3 %>% slice(-3)

myfiles = do.call(rbind.fill, lapply(datafiles, function(x) read.csv(x, sep = ";", skip = 3, header = TRUE)))

test <- myfiles %>% subset(datetime != "dt") %>%
  subset(water.temperature != "water physics") %>%
  subset(datetime != "YYYY-MM-DD hh:mm:ss") %>%
  subset(datetime != "MEZ") %>%
  subset(id != "Autogenerated Increment Value")
  
table(test$specified.depth)


# Combine into data frame
profiler_data <- do.call(rbind, lapply(datafiles, function(i) {
  print(i)
  fread(file = i, fill=TRUE)
}))



# -------
library(tidyverse)
datafiles <- list.files(path = "data/raw", 
                        pattern = ".csv", full.names = TRUE)
testdata <<- datafiles %>%
  setNames(nm = .) %>% # getting the file names from the list of files
  map_df(~read.csv(.x, sep = ";", skip = 3), .id = "file_name") %>%
  mutate(enclosure = str_extract(file_name, "[A-Za-z]\\d+")) # add a column with the enclosure number, pulled from the file name

table(testdata$enclosure)

test <- testdata %>% subset(datetime != "dt") %>%
  subset(water.temperature != "water physics") %>%
  subset(datetime != "YYYY-MM-DD hh:mm:ss") %>%
  subset(datetime != "MEZ") %>%
  subset(id != "Autogenerated Increment Value")


#------------------



# Get the list of CSV files in a directory
file_list <- datafiles

# Initialize an empty list to store data frames
data_list <- list()


# Iterate through each file
for (file in file_list) {
  # Read the CSV file
  data <- read.csv(file, sep = ";", skip = 3, header = TRUE)
  
  # Add a new column containing the original file name
  data$file_name <- file
  
  # Append the data frame to the list
  data_list[[length(data_list) + 1]] <- data
}

# Combine all data frames into a single data frame
combined_data <- do.call(rbind, data_list)



#------------------
# This is working if we don't include the L01 and L01 - need to figure out now map_dfr can deal with those pesky extra columns

datafiles2 <- list.files(path = "data/test", 
                        pattern = ".csv", full.names = TRUE)

library(dplyr)
library(purrr)

# Get the list of CSV files in a directory
file_list <- datafiles2

# Read all CSV files and add a new column with the file name
combined_data <- map_dfr(file_list, na = 'X', ~ read.csv(.x, sep = ";", skip = 3, header = TRUE) %>% mutate(file_name = .x))


#------------------

file_list <- list.files(path = "data/test", 
                         pattern = ".csv", full.names = TRUE)

# Define a function to read CSV files and add a new column with the file name
read_csv_with_filename <- function(file) {
  data <- read.csv(file, sep = ";", skip = 3, header = TRUE)
  data$file_name <- file
  return(data)
}

# Read all CSV files and bind rows, handling differing column names
combined_data <- map_dfr(file_list, read_csv_with_filename)

#------

myfiles_list <- lapply(file_list, function(x) {
  data <- read.csv(x, sep = ";", skip = 3, header = TRUE)
  data$file_name <- x
  return(data)
  })


# --------
file_list <- list.files(path = "data/test", 
                        pattern = ".csv", full.names = TRUE)



profiler_data <- do.call(rbind.fill, lapply(file_list, function(i) {
  print(i)
  read.csv(i, sep = ";", skip = 3, header = TRUE)
  
  
}))
